[package]
name = "lexer"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
core = { path = "../core/" }
log = "0.4.18"
paste = "1.0.12"
