[package]
name = "core"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
thiserror = "1.0.40"
paste = "1.0.12"
rustc-hash = "1.1.0"
